---

- name: install dnsmasq package
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - dnsmasq

- name: remove 1-router
  file: path=/etc/dnsmasq.d/1-router state=absent
  notify:
    - restart dnsmasq

- name: set dnsmasq config
  template:
    src: dnsmasq.d/1-consul.j2
    dest: /etc/dnsmasq.d/1-consul
  notify:
    - restart dnsmasq

- name: ensure dnsmasq restarted
  service: name=dnsmasq state=started

- name: set dnsmasq auto start
  service: name=dnsmasq enabled=yes
